> ###Exploratory Data Analysis
  > install.packages("dplyr")
> library(dplyr)
> first <- filter(psfd, psfd$Award == 1)
> second <- filter(psfd, psfd$Award == 2)
> noteam <- filter(psfd, psfd$Award == 0)
> AveStats_FirstTeam = aggregate(first[,5:28], list(first$Position), FUN=mean)
> AveStats_SecondTeam = aggregate(second[,5:28], list(second$Position), FUN=mean)
> AveStats_NoTeam = aggregate(noteam[,5:28], list(noteam$Position), FUN=mean)
> AveStats_FirstTeam <- as.matrix(AveStats_FirstTeam[,2:25])
> AveStats_SecondTeam <- as.matrix(AveStats_SecondTeam[,2:25])
> AveStats_NoTeam <- as.matrix(AveStats_NoTeam[,2:25])
> compareAwards <- rbind(AveStats_FirstTeam, AveStats_SecondTeam, AveStats_NoTeam)
> barplot(compareAwards, beside = TRUE, xlab = "Pitching Metric", ylab = "Performance Value", main = "Mean Pitcher Statistics Comparison between 1st, 2nd, and No Team", col = c("gold", "grey", "brown"), cex.names = .5)
> legend("topright", c("1st Team","2nd Team", "No Team"), pch=15, col=c("gold","grey", "brown"), bty="n")
### Correlation plot between numeric variables
> install.packages("corrplot")
> library(corrplot)
> psfd_cor <- cor(psfd[,4:29])
> corrplot(psfd_cor, method = "circle")
> corrplot(psfd_cor, method = "number")
###Balance Dataset with SMOTE Algorithm
> psfd$`Player ` <- as.factor(psfd$`Player `)
> psfd$Position <- as.factor(psfd$Position)
> psfd$Team <- as.factor(psfd$Team)
> psfd$Award <- as.factor(psfd$Award)
> psfd <- as.data.frame(psfd)
> balanced_ps <- SMOTE(Award ~ ., psfd, perc.over = 650, perc.under = 2500)
> summary(balanced_ps)
> write.csv(balanced_ps, "Pitching Stats Balanced Data.csv")